/**
 * Session copy shared by the browser and desktop app. Each locale implements
 * the English catalog's full shape, so missing copy fails at compile time.
 * Translation provenance: these translations are machine-quality and want a
 * native proofread, especially Albion's in-game names and currencies.
 */

import type { TLang } from "./i18n.js";
import { formatCount, plural } from "./plural.js";

const EN = {
  fame: "Fame",
  respec: "Respec",
  silver: "Silver",
  silverGross: "Gross silver",
  silverTax: "Silver tax",
  might: "Might",
  favor: "Favor",
  faction: "Faction",
  pve: "PvE",
  gathering: "Gathering",
  fishing: "Fishing",
  mobs: "Mobs",
  chests: "Chests",
  instances: "Instances",
  resources: "Resources",
  catches: "Catches",
  fish: "Fish",
  fameSources: "Fame sources",
  silverSources: "Silver sources",
  where: "Where",
  chestsOpened: "Chests opened",
  feed: "Activity feed",
  session: "Session",
  started: "Started",
  length: "Length",
  zones: "Zones",
  files: "Files",
  newSession: "New session",
  loot: "Loot",
  recentLoot: "Recent loot",
  ownLoot: "Your loot",
  nearbyLoot: "Nearby loot",
  unpriced: "Unpriced",
  notPriced: "Not priced",
  unknownZone: "Unknown zone",
  unknownMob: "Unknown mob",
  unknownItem: "Unknown item",
  unknownChest: "Unknown chest",
  unknownSource: "Unknown source",
  openWorld: "Open world",
  dungeon: "Dungeon",
  soloDungeon: "Solo dungeon",
  groupDungeon: "Group dungeon",
  roads: "Roads of Avalon",
  ancientLands: "Ancient Lands",
  mists: "Mists",
  hideout: "Hideout",
  island: "Island",
  city: "City",
  other: "Other",
  now: "Now",
  rarityCommon: "Common",
  rarityUncommon: "Uncommon",
  rarityRare: "Rare",
  rarityLegendary: "Legendary",
  auditWarning: "Some session data needs checking. Open the log files for details.",
  tableWarning: "Some places, mobs or items are not recognized yet. Their names may be missing.",
  newSessionFailure: "Couldn't start a new session. Try again.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} fame`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} silver`,
  feedKill: (name: string): string => `Defeated ${name}`,
  feedHarvest: (name: string, qty: number): string =>
    `Gathered ${plural("en", qty, { one: "# resource", few: "# resources", many: "# resources", other: "# resources" })} · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("en", qty)}`,
  feedEscape: (): string => "Fish escaped",
  feedJournal: (name: string, qty: number): string =>
    `Completed ${plural("en", qty, { one: "# journal", other: "# journals" })} · ${name}`,
  feedChest: (name: string): string => `Opened ${name}`,
  feedZone: (name: string): string => `Entered ${name}`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} picked up ${plural("en", qty, { one: "# item", few: "# items", many: "# items", other: "# items" })} · ${name}`,
  zoneCount: (n: number): string => plural("en", n, { one: "# zone", other: "# zones" }),
  killCount: (n: number): string => plural("en", n, { one: "# kill", other: "# kills" }),
  chestCount: (n: number): string => plural("en", n, { one: "# chest", other: "# chests" }),
  itemCount: (n: number): string => plural("en", n, { one: "# item", other: "# items" }),
  catchCount: (n: number): string => plural("en", n, { one: "# catch", other: "# catches" }),
  eventCount: (n: number): string => plural("en", n, { one: "# event", other: "# events" }),
};

export type TSessionStrings = typeof EN;

const UK: TSessionStrings = {
  fame: "Слава",
  respec: "Перенавчання",
  silver: "Срібло",
  silverGross: "Срібло до податку",
  silverTax: "Податок на срібло",
  might: "Міць",
  favor: "Прихильність",
  faction: "Фракція",
  pve: "PvE",
  gathering: "Збір ресурсів",
  fishing: "Риболовля",
  mobs: "Моби",
  chests: "Скрині",
  instances: "Інстанси",
  resources: "Ресурси",
  catches: "Улов",
  fish: "Риба",
  fameSources: "Джерела слави",
  silverSources: "Джерела срібла",
  where: "Де",
  chestsOpened: "Відкриті скрині",
  feed: "Стрічка подій",
  session: "Сесія",
  started: "Початок",
  length: "Тривалість",
  zones: "Зони",
  files: "Файли",
  newSession: "Нова сесія",
  loot: "Здобич",
  recentLoot: "Остання здобич",
  ownLoot: "Ваша здобич",
  nearbyLoot: "Здобич поруч",
  unpriced: "Без ціни",
  notPriced: "Ціну не визначено",
  unknownZone: "Невідома зона",
  unknownMob: "Невідомий моб",
  unknownItem: "Невідомий предмет",
  unknownChest: "Невідома скриня",
  unknownSource: "Невідоме джерело",
  openWorld: "Відкритий світ",
  dungeon: "Підземелля",
  soloDungeon: "Одиночне підземелля",
  groupDungeon: "Групове підземелля",
  roads: "Шляхи Авалону",
  ancientLands: "Стародавні землі",
  mists: "Тумани",
  hideout: "Сховище",
  island: "Острів",
  city: "Місто",
  other: "Інше",
  now: "Зараз",
  rarityCommon: "Звичайна",
  rarityUncommon: "Незвичайна",
  rarityRare: "Рідкісна",
  rarityLegendary: "Легендарна",
  auditWarning: "Деякі дані сесії потребують перевірки. Подробиці є у файлах журналу.",
  tableWarning: "Деякі місця, моби або предмети ще не розпізнано. Їхні назви можуть бути відсутні.",
  newSessionFailure: "Не вдалося розпочати нову сесію. Спробуйте ще раз.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} слави`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} срібла`,
  feedKill: (name: string): string => `Перемога над ${name}`,
  feedHarvest: (name: string, qty: number): string =>
    `Зібрано ${plural("uk", qty, { one: "# ресурс", few: "# ресурси", many: "# ресурсів", other: "# ресурсу" })} · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("uk", qty)}`,
  feedEscape: (): string => "Риба втекла",
  feedJournal: (name: string, qty: number): string =>
    `Заповнено ${plural("uk", qty, { one: "# журнал", few: "# журнали", many: "# журналів", other: "# журналу" })} · ${name}`,
  feedChest: (name: string): string => `Відкрито ${name}`,
  feedZone: (name: string): string => `Вхід у зону · ${name}`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} · підібрано ${plural("uk", qty, { one: "# предмет", few: "# предмети", many: "# предметів", other: "# предмета" })} · ${name}`,
  zoneCount: (n: number): string => plural("uk", n, { one: "# зона", few: "# зони", many: "# зон", other: "# зони" }),
  killCount: (n: number): string =>
    plural("uk", n, { one: "# вбивство", few: "# вбивства", many: "# вбивств", other: "# вбивства" }),
  chestCount: (n: number): string =>
    plural("uk", n, { one: "# скриня", few: "# скрині", many: "# скринь", other: "# скрині" }),
  itemCount: (n: number): string =>
    plural("uk", n, { one: "# предмет", few: "# предмети", many: "# предметів", other: "# предмета" }),
  catchCount: (n: number): string =>
    plural("uk", n, { one: "# улов", few: "# улови", many: "# уловів", other: "# улову" }),
  eventCount: (n: number): string =>
    plural("uk", n, { one: "# подія", few: "# події", many: "# подій", other: "# події" }),
};

const FR: TSessionStrings = {
  fame: "Renommée",
  respec: "Réattribution",
  silver: "Argent",
  silverGross: "Argent brut",
  silverTax: "Taxe sur l'argent",
  might: "Puissance",
  favor: "Faveur",
  faction: "Faction",
  pve: "JcE",
  gathering: "Récolte",
  fishing: "Pêche",
  mobs: "Monstres",
  chests: "Coffres",
  instances: "Instances",
  resources: "Ressources",
  catches: "Prises",
  fish: "Poissons",
  fameSources: "Sources de renommée",
  silverSources: "Sources d'argent",
  where: "Lieux",
  chestsOpened: "Coffres ouverts",
  feed: "Fil d'activité",
  session: "Session",
  started: "Début",
  length: "Durée",
  zones: "Zones",
  files: "Fichiers",
  newSession: "Nouvelle session",
  loot: "Butin",
  recentLoot: "Butin récent",
  ownLoot: "Votre butin",
  nearbyLoot: "Butin à proximité",
  unpriced: "Sans prix",
  notPriced: "Prix indisponible",
  unknownZone: "Zone inconnue",
  unknownMob: "Monstre inconnu",
  unknownItem: "Objet inconnu",
  unknownChest: "Coffre inconnu",
  unknownSource: "Source inconnue",
  openWorld: "Monde ouvert",
  dungeon: "Donjon",
  soloDungeon: "Donjon solo",
  groupDungeon: "Donjon de groupe",
  roads: "Routes d'Avalon",
  ancientLands: "Terres anciennes",
  mists: "Brumes",
  hideout: "Repaire",
  island: "Île",
  city: "Ville",
  other: "Autre",
  now: "Maintenant",
  rarityCommon: "Commun",
  rarityUncommon: "Inhabituel",
  rarityRare: "Rare",
  rarityLegendary: "Légendaire",
  auditWarning: "Certaines données de la session doivent être vérifiées. Consultez les fichiers journaux.",
  tableWarning: "Certains lieux, monstres ou objets ne sont pas encore reconnus. Leurs noms peuvent manquer.",
  newSessionFailure: "Impossible de démarrer une nouvelle session. Réessayez.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} de renommée`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} d'argent`,
  feedKill: (name: string): string => `Victoire contre ${name}`,
  feedHarvest: (name: string, qty: number): string =>
    `Récolte : ${plural("fr", qty, { one: "# ressource", few: "# ressources", many: "# de ressources", other: "# ressources" })} · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("fr", qty)}`,
  feedEscape: (): string => "Le poisson s'est échappé",
  feedJournal: (name: string, qty: number): string =>
    `${plural("fr", qty, { one: "# journal rempli", other: "# journaux remplis" })} · ${name}`,
  feedChest: (name: string): string => `Ouverture : ${name}`,
  feedZone: (name: string): string => `Entrée dans ${name}`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} · ramassage de ${plural("fr", qty, { one: "# objet", few: "# objets", many: "# d'objets", other: "# objets" })} · ${name}`,
  zoneCount: (n: number): string => plural("fr", n, { one: "# zone", many: "# de zones", other: "# zones" }),
  killCount: (n: number): string =>
    plural("fr", n, { one: "# élimination", many: "# d'éliminations", other: "# éliminations" }),
  chestCount: (n: number): string => plural("fr", n, { one: "# coffre", many: "# de coffres", other: "# coffres" }),
  itemCount: (n: number): string => plural("fr", n, { one: "# objet", many: "# d'objets", other: "# objets" }),
  catchCount: (n: number): string => plural("fr", n, { one: "# prise", many: "# de prises", other: "# prises" }),
  eventCount: (n: number): string =>
    plural("fr", n, { one: "# événement", many: "# d'événements", other: "# événements" }),
};

const RU: TSessionStrings = {
  fame: "Слава",
  respec: "Переобучение",
  silver: "Серебро",
  silverGross: "Серебро до налога",
  silverTax: "Налог на серебро",
  might: "Могущество",
  favor: "Благосклонность",
  faction: "Фракция",
  pve: "PvE",
  gathering: "Сбор ресурсов",
  fishing: "Рыбалка",
  mobs: "Мобы",
  chests: "Сундуки",
  instances: "Инстансы",
  resources: "Ресурсы",
  catches: "Улов",
  fish: "Рыба",
  fameSources: "Источники славы",
  silverSources: "Источники серебра",
  where: "Где",
  chestsOpened: "Открытые сундуки",
  feed: "Лента событий",
  session: "Сессия",
  started: "Начало",
  length: "Длительность",
  zones: "Зоны",
  files: "Файлы",
  newSession: "Новая сессия",
  loot: "Добыча",
  recentLoot: "Последняя добыча",
  ownLoot: "Ваша добыча",
  nearbyLoot: "Добыча рядом",
  unpriced: "Без цены",
  notPriced: "Цена не определена",
  unknownZone: "Неизвестная зона",
  unknownMob: "Неизвестный моб",
  unknownItem: "Неизвестный предмет",
  unknownChest: "Неизвестный сундук",
  unknownSource: "Неизвестный источник",
  openWorld: "Открытый мир",
  dungeon: "Подземелье",
  soloDungeon: "Одиночное подземелье",
  groupDungeon: "Групповое подземелье",
  roads: "Пути Авалона",
  ancientLands: "Древние земли",
  mists: "Туманы",
  hideout: "Убежище",
  island: "Остров",
  city: "Город",
  other: "Другое",
  now: "Сейчас",
  rarityCommon: "Обычная",
  rarityUncommon: "Необычная",
  rarityRare: "Редкая",
  rarityLegendary: "Легендарная",
  auditWarning: "Некоторые данные сессии требуют проверки. Подробности есть в файлах журнала.",
  tableWarning: "Некоторые места, мобы или предметы ещё не распознаны. Их названия могут отсутствовать.",
  newSessionFailure: "Не удалось начать новую сессию. Попробуйте ещё раз.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} славы`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} серебра`,
  feedKill: (name: string): string => `Победа над ${name}`,
  feedHarvest: (name: string, qty: number): string =>
    `Собрано ${plural("ru", qty, { one: "# ресурс", few: "# ресурса", many: "# ресурсов", other: "# ресурса" })} · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("ru", qty)}`,
  feedEscape: (): string => "Рыба уплыла",
  feedJournal: (name: string, qty: number): string =>
    `Заполнено ${plural("ru", qty, { one: "# журнал", few: "# журнала", many: "# журналов", other: "# журнала" })} · ${name}`,
  feedChest: (name: string): string => `Открыто ${name}`,
  feedZone: (name: string): string => `Вход в зону · ${name}`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} · подобрано ${plural("ru", qty, { one: "# предмет", few: "# предмета", many: "# предметов", other: "# предмета" })} · ${name}`,
  zoneCount: (n: number): string => plural("ru", n, { one: "# зона", few: "# зоны", many: "# зон", other: "# зоны" }),
  killCount: (n: number): string =>
    plural("ru", n, { one: "# убийство", few: "# убийства", many: "# убийств", other: "# убийства" }),
  chestCount: (n: number): string =>
    plural("ru", n, { one: "# сундук", few: "# сундука", many: "# сундуков", other: "# сундука" }),
  itemCount: (n: number): string =>
    plural("ru", n, { one: "# предмет", few: "# предмета", many: "# предметов", other: "# предмета" }),
  catchCount: (n: number): string =>
    plural("ru", n, { one: "# улов", few: "# улова", many: "# уловов", other: "# улова" }),
  eventCount: (n: number): string =>
    plural("ru", n, { one: "# событие", few: "# события", many: "# событий", other: "# события" }),
};

const PT: TSessionStrings = {
  fame: "Fama",
  respec: "Redistribuição",
  silver: "Prata",
  silverGross: "Prata bruta",
  silverTax: "Imposto sobre a prata",
  might: "Poder",
  favor: "Favor",
  faction: "Facção",
  pve: "PvE",
  gathering: "Coleta",
  fishing: "Pesca",
  mobs: "Monstros",
  chests: "Baús",
  instances: "Instâncias",
  resources: "Recursos",
  catches: "Capturas",
  fish: "Peixes",
  fameSources: "Fontes de fama",
  silverSources: "Fontes de prata",
  where: "Locais",
  chestsOpened: "Baús abertos",
  feed: "Atividades recentes",
  session: "Sessão",
  started: "Início",
  length: "Duração",
  zones: "Zonas",
  files: "Arquivos",
  newSession: "Nova sessão",
  loot: "Saque",
  recentLoot: "Saque recente",
  ownLoot: "Seu saque",
  nearbyLoot: "Saque próximo",
  unpriced: "Sem preço",
  notPriced: "Preço indisponível",
  unknownZone: "Zona desconhecida",
  unknownMob: "Monstro desconhecido",
  unknownItem: "Item desconhecido",
  unknownChest: "Baú desconhecido",
  unknownSource: "Fonte desconhecida",
  openWorld: "Mundo aberto",
  dungeon: "Masmorra",
  soloDungeon: "Masmorra solo",
  groupDungeon: "Masmorra de grupo",
  roads: "Estradas de Avalon",
  ancientLands: "Terras Antigas",
  mists: "Brumas",
  hideout: "Esconderijo",
  island: "Ilha",
  city: "Cidade",
  other: "Outro",
  now: "Agora",
  rarityCommon: "Comum",
  rarityUncommon: "Incomum",
  rarityRare: "Raro",
  rarityLegendary: "Lendário",
  auditWarning: "Alguns dados da sessão precisam ser conferidos. Veja os arquivos de registro.",
  tableWarning: "Alguns locais, monstros ou itens ainda não são reconhecidos. Seus nomes podem estar ausentes.",
  newSessionFailure: "Não foi possível iniciar uma nova sessão. Tente novamente.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} de fama`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} de prata`,
  feedKill: (name: string): string => `Vitória contra ${name}`,
  feedHarvest: (name: string, qty: number): string =>
    `Coleta: ${plural("pt", qty, { one: "# recurso", few: "# recursos", many: "# de recursos", other: "# recursos" })} · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("pt", qty)}`,
  feedEscape: (): string => "O peixe escapou",
  feedJournal: (name: string, qty: number): string =>
    `${plural("pt", qty, { one: "# diário preenchido", other: "# diários preenchidos" })} · ${name}`,
  feedChest: (name: string): string => `Abertura: ${name}`,
  feedZone: (name: string): string => `Entrada em ${name}`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} · recolheu ${plural("pt", qty, { one: "# item", few: "# itens", many: "# de itens", other: "# itens" })} · ${name}`,
  zoneCount: (n: number): string => plural("pt", n, { one: "# zona", many: "# de zonas", other: "# zonas" }),
  killCount: (n: number): string => plural("pt", n, { one: "# abate", many: "# de abates", other: "# abates" }),
  chestCount: (n: number): string => plural("pt", n, { one: "# baú", many: "# de baús", other: "# baús" }),
  itemCount: (n: number): string => plural("pt", n, { one: "# item", many: "# de itens", other: "# itens" }),
  catchCount: (n: number): string => plural("pt", n, { one: "# captura", many: "# de capturas", other: "# capturas" }),
  eventCount: (n: number): string => plural("pt", n, { one: "# evento", many: "# de eventos", other: "# eventos" }),
};

const DE: TSessionStrings = {
  fame: "Ruhm",
  respec: "Umschulung",
  silver: "Silber",
  silverGross: "Bruttosilber",
  silverTax: "Silbersteuer",
  might: "Macht",
  favor: "Gunst",
  faction: "Fraktion",
  pve: "PvE",
  gathering: "Sammeln",
  fishing: "Angeln",
  mobs: "Monster",
  chests: "Truhen",
  instances: "Instanzen",
  resources: "Ressourcen",
  catches: "Fänge",
  fish: "Fische",
  fameSources: "Ruhmquellen",
  silverSources: "Silberquellen",
  where: "Orte",
  chestsOpened: "Geöffnete Truhen",
  feed: "Aktivitätsverlauf",
  session: "Sitzung",
  started: "Beginn",
  length: "Dauer",
  zones: "Gebiete",
  files: "Dateien",
  newSession: "Neue Sitzung",
  loot: "Beute",
  recentLoot: "Letzte Beute",
  ownLoot: "Deine Beute",
  nearbyLoot: "Beute in der Nähe",
  unpriced: "Ohne Preis",
  notPriced: "Preis unbekannt",
  unknownZone: "Unbekanntes Gebiet",
  unknownMob: "Unbekanntes Monster",
  unknownItem: "Unbekannter Gegenstand",
  unknownChest: "Unbekannte Truhe",
  unknownSource: "Unbekannte Quelle",
  openWorld: "Offene Welt",
  dungeon: "Verlies",
  soloDungeon: "Soloverlies",
  groupDungeon: "Gruppenverlies",
  roads: "Straßen von Avalon",
  ancientLands: "Uralte Länder",
  mists: "Nebel",
  hideout: "Versteck",
  island: "Insel",
  city: "Stadt",
  other: "Sonstiges",
  now: "Jetzt",
  rarityCommon: "Gewöhnlich",
  rarityUncommon: "Ungewöhnlich",
  rarityRare: "Selten",
  rarityLegendary: "Legendär",
  auditWarning: "Einige Sitzungsdaten müssen geprüft werden. Details stehen in den Protokolldateien.",
  tableWarning: "Einige Orte, Gegner oder Gegenstände werden noch nicht erkannt. Ihre Namen können fehlen.",
  newSessionFailure: "Eine neue Sitzung konnte nicht gestartet werden. Versuche es erneut.",
  feedFame: (name: string, amount: string | number): string => `${name} · +${amount} Ruhm`,
  feedSilver: (name: string, amount: string | number): string => `${name} · +${amount} Silber`,
  feedKill: (name: string): string => `${name} besiegt`,
  feedHarvest: (name: string, qty: number): string =>
    `${plural("de", qty, { one: "# Ressource", few: "# Ressourcen", many: "# Ressourcen", other: "# Ressourcen" })} gesammelt · ${name}`,
  feedFish: (name: string, qty: number): string => `${name} ×${formatCount("de", qty)}`,
  feedEscape: (): string => "Fisch entkommen",
  feedJournal: (name: string, qty: number): string =>
    `${plural("de", qty, { one: "# Tagebuch gefüllt", other: "# Tagebücher gefüllt" })} · ${name}`,
  feedChest: (name: string): string => `${name} geöffnet`,
  feedZone: (name: string): string => `${name} betreten`,
  feedLoot: (looter: string, name: string, qty: number): string =>
    `${looter} · ${plural("de", qty, { one: "# Gegenstand", few: "# Gegenstände", many: "# Gegenstände", other: "# Gegenstände" })} aufgehoben · ${name}`,
  zoneCount: (n: number): string => plural("de", n, { one: "# Gebiet", other: "# Gebiete" }),
  killCount: (n: number): string => plural("de", n, { one: "# Abschuss", other: "# Abschüsse" }),
  chestCount: (n: number): string => plural("de", n, { one: "# Truhe", other: "# Truhen" }),
  itemCount: (n: number): string => plural("de", n, { one: "# Gegenstand", other: "# Gegenstände" }),
  catchCount: (n: number): string => plural("de", n, { one: "# Fang", other: "# Fänge" }),
  eventCount: (n: number): string => plural("de", n, { one: "# Ereignis", other: "# Ereignisse" }),
};

const CATALOG: Record<TLang, TSessionStrings> = { en: EN, uk: UK, fr: FR, ru: RU, pt: PT, de: DE };

export const sessionStrings = (lang: TLang): TSessionStrings => CATALOG[lang];
