/** Regenerate committed data: node tools/session-names.mjs <dump-folder> <revision>.
 * Inputs: clusters.json (cluster/world.json), mobs.json, localization.json, worldsettings.json.
 * No runtime download, no extracted art. Numeric mobs retain file order + the game's 16-slot offset.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";
export const MOB_OFFSET = 16;
const list = (value) => (value == null ? [] : Array.isArray(value) ? value : [value]);
export const generateNames = ({ clusters, mobs, localization, settings }) => {
  const translations = new Map(
    list(localization.tmx.body.tu).map((row) => [
      row["@tuid"],
      Object.fromEntries(
        list(row.tuv)
          .filter((t) => typeof t.seg === "string")
          .map((t) => [t["@xml:lang"], t.seg]),
      ),
    ]),
  );
  const locales = { en: "EN-US", de: "DE-DE", fr: "FR-FR", ru: "RU-RU", pt: "PT-BR" };
  const namesFor = (tag) =>
    Object.fromEntries(
      Object.entries(locales).flatMap(([lang, locale]) =>
        translations.get(tag)?.[locale] ? [[lang, translations.get(tag)[locale]]] : [],
      ),
    );
  const types = new Map(
    list(settings["AO-WorldSettings"].clustertypes.clustertype).map((type) => [type["@name"], type]),
  );
  const world = {};
  for (const row of list(clusters.world.clusters.cluster)) {
    const type = row["@type"] ?? "";
    const archetype = types.get(type)?.["@archetype"] ?? "";
    const colour = /^(GREEN|YELLOW|RED|BLACK)(?:_|$)/.exec(archetype)?.[1].toLowerCase() ?? null;
    const tier = /_T([1-8])_/.exec(row["@file"] ?? "")?.[1];
    const content =
      type.startsWith("CITY") || type.startsWith("PLAYERCITY") || type === "STARTINGCITY"
        ? "city"
        : type.includes("ISLAND")
          ? "island"
          : type.includes("HIDEOUT")
            ? "hideout"
            : type.startsWith("TUNNEL") || type.includes("ROAD") || type.includes("AVALON")
              ? "roads"
              : type.includes("MIST")
                ? "mists"
                : type.includes("DRAGON")
                  ? "ancientLands"
                  : types.get(type)?.["@isdungeon"] === "true"
                    ? "dungeon"
                    : type.startsWith("START") || type.startsWith("TUTORIAL")
                      ? "other"
                      : "openWorld";
    const label = row["@displayname"];
    world[row["@id"]] = {
      name: label?.startsWith("@") ? (namesFor(label).en ?? null) : label || null,
      tier: tier == null ? null : Number(tier),
      colour,
      content,
    };
  }
  const mobTable = {};
  const identities = new Map();
  for (const row of list(mobs.Mobs.Mob)) {
    if (row["@namelocatag"]) {
      const key = `${row["@faction"]}:${row["@avatar"]}`;
      const tags = identities.get(key) ?? new Set();
      tags.add(row["@namelocatag"]);
      identities.set(key, tags);
    }
  }
  list(mobs.Mobs.Mob).forEach((row, index) => {
    const identity = identities.get(`${row["@faction"]}:${row["@avatar"]}`);
    const tag =
      row["@namelocatag"] ??
      (translations.has(`@MOB_${row["@uniquename"]}`)
        ? `@MOB_${row["@uniquename"]}`
        : identity?.size === 1
          ? [...identity][0]
          : null);
    mobTable[index + MOB_OFFSET] = {
      unique: row["@uniquename"],
      names: namesFor(tag),
      tier: row["@tier"] == null ? null : Number(row["@tier"]),
      faction: row["@faction"] ?? null,
      avatar: row["@avatar"] ?? null,
    };
  });
  const items = Object.fromEntries(
    [...translations.keys()]
      .filter((tag) => /^@ITEMS_T[1-8]_(?:ORE|WOOD|HIDE|FIBER|ROCK|FISH|SEAWEED|JOURNAL)(?:_|$)/.test(tag))
      // This slice observes completed books; descriptions/empty/partial books have no consumer.
      .filter((tag) => !tag.includes("_JOURNAL_") || tag.endsWith("_FULL"))
      .map((tag) => [tag.slice(7), namesFor(tag)]),
  );
  return { world, mobs: mobTable, items };
};
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [dir, revision] = process.argv.slice(2);
  if (!dir || !/^[a-f0-9]{40}$/.test(revision ?? "")) {
    throw new Error("Usage: node tools/session-names.mjs <dump-folder> <40-character revision>");
  }
  const inputs = Object.fromEntries(
    ["clusters", "mobs", "localization", "worldsettings"].map((key) => [
      key === "worldsettings" ? "settings" : key,
      JSON.parse(readFileSync(join(dir, `${key}.json`), "utf8")),
    ]),
  );
  const tables = generateNames(inputs);
  const destination = new URL("../src/shared/session/nameTables.ts", import.meta.url);
  const source = `// Generated by tools/session-names.mjs; ao-data/ao-bin-dumps@${revision}. Do not edit.\nimport type { TMobName, TWorldName } from './names.js';\nimport type { TLang } from '../i18n.js';\nexport const WORLD: Record<string, TWorldName> = ${JSON.stringify(tables.world)};\nexport const MOBS: Record<string, TMobName> = ${JSON.stringify(tables.mobs)};\nexport const RESOURCE_NAMES: Record<string, Partial<Record<TLang, string>>> = ${JSON.stringify(tables.items)};\n`;
  writeFileSync(destination, source);
  const sha256 = (text) => createHash("sha256").update(text).digest("hex");
  const manifest = {
    revision,
    source: `https://github.com/ao-data/ao-bin-dumps/tree/${revision}`,
    mobOffset: MOB_OFFSET,
    worldCount: Object.keys(tables.world).length,
    mobCount: Object.keys(tables.mobs).length,
    tableSha256: sha256(source),
    inputSha256: Object.fromEntries(
      ["clusters", "mobs", "localization", "worldsettings"].map((key) => [
        key,
        sha256(readFileSync(join(dir, `${key}.json`))),
      ]),
    ),
  };
  mkdirSync(new URL("../docs/", import.meta.url), { recursive: true });
  writeFileSync(new URL("../docs/session-names.json", import.meta.url), JSON.stringify(manifest, null, 2) + "\n");
  console.log(`World: ${manifest.worldCount}, mobs: ${manifest.mobCount}; ${manifest.tableSha256}`);
}
